name: Check Theme (GScan)
on:
  pull_request:
    branches:
      - master
jobs:
  check-compatibility:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 16
    - name: Install gscan
      run: npm install -g gscan
    - name: Build theme
      run: npm install
    - name: Pack theme
      run: npm run zip
    - name: Scan for compatibility issues
      run: gscan -z ./samueleresca-ui.zip