name: Check Theme (GScan)
on:
  push:
  pull_request:
    branches:
      - master
jobs:
  check-compatibility:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install gscan
      run: npm install -g gscan
    - name: Build theme
      working-directory: ./src
      run: npm run production
    - name: Scan for compatibility issues
      working-directory: ./src
      run: gscan ./samueleresca-ui.zip