name: Deploy Theme
on:
  push:
    branches:
    - master
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: npm install
        working-directory: ./src
      - name: Build theme
        working-directory: ./src
        run: npm run production
      - name: 'Deploy Ghost Theme'
        run: node src/deploy/index.js
        env:
          url: ${{ secrets.GHOST_ADMIN_API_URL }}
          key: ${{ secrets.GHOST_ADMIN_API_KEY }}
